[workspace]
resolver = "2"

exclude = [
    "external/ext-0",
]

members = [
    "crates/layer-0",
    "crates/layer-1",
    "crates/layer-2",
]

[workspace.package]
version = "0.32.0"

[workspace.dependencies]
external = { path = "external/ext-0" }
