[package]
name = "layer-1"
version = "0.1.0"
edition = "2021"

[dependencies]
ext-0.workspace = true
layer-0.path = "../layer-0"
layer-1-v1 = { path = "../layer-1-latest", package = "layer-1-latest" }
